// Code generated by "stringer -type=CountryType"; DO NOT EDIT

package main

import "fmt"

const _CountryType_name = "ussg"

var _CountryType_index = [...]uint8{0, 2, 4}

func (i CountryType) String() string {
	if i < 0 || i >= CountryType(len(_CountryType_index)-1) {
		return fmt.Sprintf("CountryType(%d)", i)
	}
	return _CountryType_name[_CountryType_index[i]:_CountryType_index[i+1]]
}
