// Code generated by "stringer -type=EventType"; DO NOT EDIT

package main

import "fmt"

const _EventType_name = "e.DoWorke.PQOpene.Finishede.AppendFreeConn"

var _EventType_index = [...]uint8{0, 8, 16, 26, 42}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
